### PR TITLE
Merge pull request #12 from cookiemonsterleni/master

### PR DESCRIPTION
**Pull request by epartakki**
Merge pull request #11 from cookiemonsterleni/EleniC

### CODE REVIEW

**Review by supersam654 — COMMENTED** [review]
It looks like there aren't any changes is this pull request (because they've already been merged in). Is that what you were expecting or are there supposed to be changes here?

**Comment by epartakki** [comment]
> It looks like there aren't any changes is this pull request (because they've already been merged in). Is that what you were expecting or are there supposed to be changes here?

I am not sure what is happening with the merge. Are you able to see my changes from Week 2?

**Comment by supersam654** [comment]
Are you talking about the changes in https://github.com/cookiemonsterleni/software-product-sprint/pull/11 or something else?

**Review by epartakki — COMMENTED** [review]
no changes?

**Pull request closed without merging**
